import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 追加ここから：Google Analyticsを使うための準備
import { GoogleAnalytics } from '@next/third-parties/google'
// 追加ここまで

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* 追加ここから：測定IDを設置 */}
        <GoogleAnalytics gaId="G-R7YCDM84C0" />
        {/* 追加ここまで */}
      </body>
    </html>
  );
}

// update